### ISSUE TITLE
Compatibility with PHP 7

### ISSUE THREAD

**Issue by AnaelMobilia** [cosmocode/dokuwiki-plugin-note#1]
Hello,

Error message :
Warning: Declaration of syntax_plugin_note::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /data/www/wiki/lib/plugins/note/syntax.php on line 188

Warning: Declaration of syntax_plugin_note::render($mode, &$renderer, $indata) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in /data/www/wiki/lib/plugins/note/syntax.php on line 188

Server : centos 7 / php-fpm 7 / dokuwiki 2015-08-10a "Detritus"

**Comment by HanPrower** [comment]
I think I've fixed this.

Open the syntax.php in /lib/plugins/note and change the &$handler and &$renderer to Doku_Handler $handler and Doku_Renderer $renderer respectively.

I could be wrong though, but the error has gone and the plugin still works, so... yea.
